const clusterData = [
  {
    id: 1,
    image: '/assets/agriculture.png',
    name: 'Agriculture',
    subtitle: 'Agriculture, food and natural resources',
    keywords: [],
    careers:[],
  },
  {
    id: 2,
    image: '/assets/architecture.png',
    name: 'Architecture',
    subtitle: 'Architecture and construction',
    keywords: [],
    careers:[],
  },
  {
    id: 3,
    image: '/assets/arts.png',
    name: 'Arts',
    subtitle: 'Arts, audio/video technology, and communications',
    keywords: [],
    careers:[],
  },
  {
    id: 4,
    image: '/assets/business.png',
    name: 'Business',
    subtitle: 'Business management and administration ',
    keywords: [],
    careers:[],
  },
  {
    id: 5,
    image: '/assets/education.png',
    name: 'Education',
    subtitle: 'Education and training',
    keywords: [],
    careers:[],
  },
  {
    id: 6,
    image: '/assets/finance.png',
    name: 'Finance',
    subtitle: 'Finance',
    keywords: [],
    careers:[],
  },
  {
    id: 7,
    image: '/assets/government.png',
    name: 'Government',
    subtitle: 'Government and public administration',
  keywords: [],careers:[],},
  {
    id: 8,
    image: '/assets/health_sciences.png',
    name: 'Health',
    subtitle: 'Health sciences',
    keywords: [],
    careers:[],
  },
  {
    id: 9,
    image: '/assets/hospitality.png',
    name: 'Hospitality',
    subtitle: 'Hospitality and tourism',
    keywords: [],
    careers:[],
  },
  {
    id: 10,
    image: '/assets/human_services.png',
    name: 'Human services',
    subtitle: 'Human services',
    keywords: [],
    careers:[],
  },
  {
    id: 11,
    image: '/assets/information_technology.png',
    name: 'Information technology',
    subtitle: 'Information technology',
    keywords: [],
    careers:[],
  },
  {
    id: 12,
    image: '/assets/law.png',
    name: 'Law',
    subtitle: 'Law, public safety, corrections, and security',
    keywords: [],
    careers:[],
  },
  {
    id: 13,
    image: '/assets/manufacturing.png',
    name: 'Manufacturing',
    subtitle: 'Manufacturing',
  keywords: [],careers:[],},
  {
    id: 14,
    image: '/assets/marketing.png',
    name: 'Marketing',
    subtitle: 'Marketing',
    keywords: [],
    careers:[],
  },
  {
    id: 15,
    image: '/assets/stem.png',
    name: 'STEM',
    subtitle: 'Science, technology, engineering, and mathematics',
  keywords: [],careers:[],},
  {
    id: 16,
    image: '/assets/transportation.png',
    name: 'Transportation',
    subtitle: 'Transportation, distribution, and logistics',
    keywords: [],
    careers:[],
  },
];

module.exports = clusterData;